"use client";

import React, { useState, useEffect } from "react";
import { LLMRenderer, generateUIFromPrompt } from "@/system/llm_renderer";
import { Sparkles } from "lucide-react";
import { ErrorBoundary } from "@/components/common/ErrorBoundary";

export const GenerativeUIApp = ({ prompt }: { prompt: string }) => {
    const [schema, setSchema] = useState<any>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const load = async () => {
            setLoading(true);
            try {
                const ui = await generateUIFromPrompt(prompt);
                setSchema(ui);
            } catch (e) {
                console.error("Generative UI Error:", e);
                // Error boundary will catch this if we re-throw or if it happens in render
            } finally {
                setLoading(false);
            }
        };
        load();
    }, [prompt]);

    return (
        <ErrorBoundary>
            <div className="h-full w-full bg-black text-slate-200 overflow-y-auto">
                {loading ? (
                    <div className="flex flex-col items-center justify-center h-full space-y-4">
                        <Sparkles className="animate-spin text-purple-500" size={32} />
                        <div className="text-sm font-mono text-purple-400">Generative AI is dreaming up interface...</div>
                    </div>
                ) : (
                    <div className="relative">
                        <div className="absolute top-2 right-2 text-[10px] bg-purple-500/10 text-purple-400 px-2 py-1 rounded border border-purple-500/20 uppercase tracking-widest flex items-center gap-1">
                            <Sparkles size={10} /> Generated by Synapse LLM
                        </div>
                        {schema && <LLMRenderer schema={schema} />}
                    </div>
                )}
            </div>
        </ErrorBoundary>
    );
};
